### ISSUE TITLE
webhook是需要pro吗，没找到填的地方

### ISSUE THREAD

**Issue by tlightsky** [lepture/tower-slack#1]
如题

**Comment by lepture** [comment]
@tlightsky 你说的是 tower 的 webhook 还是 Slack 的 webhook

两者普通用户都可以使用。

**Comment by tlightsky** [comment]
拿到了slack的incoming webhook，不知道填到tower的什么地方

**Comment by tlightsky** [comment]
就这样关了啊＝ ＝，
![这张](https://cloud.githubusercontent.com/assets/290496/10625797/59b64710-77da-11e5-90dc-e496113aceab.png)
所以这张图到底是哪个url

**Comment by lepture** [comment]
settings

**Comment by tlightsky** [comment]
no，可能功能还没上线吧
